# Generated by Django 5.1.4 on 2026-05-09 01:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Is Popular')),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=100, verbose_name='Size/Variant')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Purchase Cost')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stock Quantity')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
            },
        ),
    ]
