# Generated by Django 5.1.4 on 2026-05-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['price'], 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
    ]
