# Generated by Django 5.1.4 on 2026-05-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderrating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order Rating', 'verbose_name_plural': 'Order Ratings'},
        ),
    ]
