# Generated by Django 5.1.4 on 2026-05-09 01:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='File')),
                ('url', models.URLField(blank=True, verbose_name='Direct URL')),
                ('file_type', models.CharField(max_length=100, verbose_name='File Type')),
                ('size', models.IntegerField(verbose_name='File Size (Bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
            },
        ),
    ]
