# Generated by Django 5.1.4 on 2026-05-09 01:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Store Name')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='Logo URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Store Description')),
                ('category', models.CharField(max_length=100, verbose_name='Store Category')),
                ('rating', models.FloatField(default=0.0, verbose_name='Rating')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('location_lng', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('icon', models.CharField(help_text='Material Design Icon name', max_length=50, verbose_name='Category Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='stores.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
