# Generated by Django 5.1.4 on 2026-05-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Store Category'),
        ),
    ]
