# Generated by Django 5.1.4 on 2026-05-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='store',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
    ]
