# Generated by Django 5.1.4 on 2026-05-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_phone_number_store_whatsapp_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created_at'], 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
    ]
